name: CD - Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar credenciais AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login no AWS ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com

      - name: Criar imagem Docker e enviar para o ECR
        run: |
          docker build -t fake-twitter-backend .
          docker tag fake-twitter-backend:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/fake-twitter-backend:latest
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/fake-twitter-backend:latest

      - name: Atualizar serviço no ECS
        run: |
          aws ecs update-service \
            --cluster FakeTwitterStack-FakeTwitterCluster39D9425E-0ZyVOHooplgC \
            --service FakeTwitterStack-BackendService2147DAF9-hiAsc9Skl8AZ \
            --force-new-deployment
            
